---
title: "NDF Fractions Reference"
author: "GEMS Cornell"
date: "`r format(Sys.Date())`"
output:
  html_document:
    toc: true
    toc_depth: 2
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,      # hides code
  message = FALSE,   # hides messages
  warning = FALSE    # hides warnings
)
```



```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(dplyr)
library(gt)          # nice-looking tables
```


```{r}
# ▶ Embedded NDF data (no CSV dependency)

ndf <- tibble::tibble(
Abbreviation = c("NDF", "aNDF", "NDFom", "aNDFom"),
`Full Name` = c(
"Neutral Detergent Fiber",
"Amylase-treated Neutral Detergent Fiber",
"Ash-free Neutral Detergent Fiber",
"Amylase-treated, ash-free NDF"
),
Definition = c(
"Residue after neutral detergent; includes cellulose, hemicellulose, lignin, ash.",
"NDF determined with heat-stable α-amylase to remove starch contamination.",
"NDF expressed on an organic matter basis (ash-free).",
"NDF with α-amylase treatment and expressed ash-free."
),
`Notes / Usage` = c(
"Intake regulator; base measurement.",
"More accurate; recommended.",
"Corrects for residual mineral content.",
"International standard (AOAC/ISO/ICAR)."
)
)

```

```{r}
ndf |>
gt() |>
tab_header(
title = md("**Neutral Detergent Fiber (NDF) Fractions**"),
subtitle = "Standard terms used in the GEMS Data Entry Template"
) |>
tab_options(
table.font.size = px(14),
data_row.padding = px(6),
table.width = pct(100),            # make table span full page width
container.width = pct(100)         # remove scrolling in HTML
) |>
fmt_markdown(everything())


```


