# Databricks notebook source
# MAGIC %md
# MAGIC Purpose
# MAGIC
# MAGIC This notebook sends automated notification emails to contributors based on validation and QC results prepared earlier in the GEMS data pipeline. The goal is to ensure that Data Managers and contributors receive timely feedback about the status of their submitted study workbooks, including any missing data, validation failures, or quality control issues that must be corrected.
# MAGIC
# MAGIC While earlier pipeline steps generate the validation outcomes and prepare email messages in the operational queue (opsEmailQueueQc), this notebook performs the actual email delivery. It retrieves the prepared messages, sends them to the appropriate recipients using Gmail SMTP, and records the sending status for monitoring and auditing.
# MAGIC
# MAGIC Main Tasks
# MAGIC
# MAGIC Initialize Email Sending Environment
# MAGIC The notebook initializes the configuration required to send emails through Gmail SMTP. It also checks whether the operational queue table contains the required tracking columns used to monitor email delivery.
# MAGIC
# MAGIC These columns include:
# MAGIC
# MAGIC sendStatus  
# MAGIC sentTsUtc  
# MAGIC sendError  
# MAGIC
# MAGIC If any of these columns are missing, they are automatically added to the table to ensure the pipeline can record the outcome of each email attempt.
# MAGIC
# MAGIC Retrieve the Latest Email Run
# MAGIC The notebook identifies the most recent email batch using the emailRunId stored in the email queue table.
# MAGIC
# MAGIC This step ensures that the notebook processes only the emails generated during the latest pipeline execution, preventing older notifications from being resent.
# MAGIC
# MAGIC Select Pending Emails
# MAGIC From the latest email run, the notebook selects only the messages that still need to be sent.
# MAGIC
# MAGIC The filtering logic ensures that:
# MAGIC
# MAGIC only the latest record per study submission is considered  
# MAGIC emails that already have sendStatus = SENT are skipped  
# MAGIC only unsent or previously failed messages are processed  
# MAGIC
# MAGIC This prevents duplicate notifications from being sent.
# MAGIC
# MAGIC Construct Email Messages
# MAGIC For each selected record, the notebook constructs a plain-text email message containing:
# MAGIC
# MAGIC sender address  
# MAGIC recipient (toEmail)  
# MAGIC optional CC recipients (ccEmails)  
# MAGIC subject line (emailSubject)  
# MAGIC email content (emailBody)  
# MAGIC
# MAGIC Plain text formatting is used to preserve line breaks and ensure compatibility with common email clients such as Outlook.
# MAGIC
# MAGIC Send Emails via SMTP
# MAGIC The notebook connects to the Gmail SMTP server and sends each prepared email message.
# MAGIC
# MAGIC Each message is sent to the primary recipient and any additional CC recipients. The sending process uses secure SMTP authentication with an application password.
# MAGIC
# MAGIC Record Email Delivery Results
# MAGIC After each sending attempt, the notebook updates the email queue table with the result of the operation.
# MAGIC
# MAGIC The following fields are written to opsEmailQueueQc:
# MAGIC
# MAGIC sendStatus (SENT or FAILED)  
# MAGIC sentTsUtc (timestamp of the sending attempt)  
# MAGIC sendError (error message if the email failed)  
# MAGIC
# MAGIC This table therefore serves as a complete audit log of email notifications generated by the pipeline.
# MAGIC
# MAGIC Output and Next Step
# MAGIC
# MAGIC The primary output of this notebook is the updated opsEmailQueueQc table, which records the delivery status of each notification email.
# MAGIC
# MAGIC Successful deliveries confirm that contributors have received feedback about their study submission. If errors occur, they are captured in the queue table so that the issue can be diagnosed and the notification can be resent if necessary.
# MAGIC
# MAGIC These notifications guide contributors to correct any missing data or QC violations identified earlier in the pipeline. Once corrections are made and the workbook is resubmitted, the validation and QC process can run again, allowing the study to proceed toward Gold-layer processing and final dataset integration.

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 0 — Setup + ensure send-tracking columns exist

# COMMAND ----------

from datetime import datetime, timezone
import re
import getpass
import smtplib

from email.message import EmailMessage
from pyspark.sql import functions as F

catalog = "gems_catalog"
schema  = "gems_schema"

emailQueueQcTable = f"{catalog}.{schema}.opsEmailQueueQc"

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT   = 587

DEFAULT_FROM_EMAIL = "no-reply@bovi-analytics.org"
DEFAULT_REPLY_TO   = "no-reply@bovi-analytics.org"

MAX_EMAILS_PER_RUN = 200
DRY_RUN = False


existing_cols = {c.name.lower() for c in spark.catalog.listColumns(emailQueueQcTable)}

required_cols = {
    "sendstatus": "STRING",
    "senttsutc": "TIMESTAMP",
    "senderror": "STRING"
}

for col_lc, dtype in required_cols.items():

    if col_lc not in existing_cols:

        col_name = {
            "sendstatus":"sendStatus",
            "senttsutc":"sentTsUtc",
            "senderror":"sendError"
        }[col_lc]

        print(f"Adding missing column: {col_name}")

        spark.sql(f"""
        ALTER TABLE {emailQueueQcTable}
        ADD COLUMNS ({col_name} {dtype})
        """)

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 1 — Prompt for Gmail App Password

# COMMAND ----------

SMTP_PASSWORD = getpass.getpass(
    "Paste Gmail App Password for no-reply@bovi-analytics.org: "
)

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 2 — Helpers

# COMMAND ----------

def sanitize_text(s):

    if s is None:
        return ""

    s = str(s)
    s = s.replace("\x00","")
    s = s.replace("\xa0"," ")

    return s.strip()


def clean_email(addr):

    if addr is None:
        return ""

    addr = sanitize_text(addr)
    addr = addr.replace(" ","")

    if "@" not in addr:
        return ""

    return addr


def esc_sql(val):

    if val is None:
        return ""

    return sanitize_text(val).replace("'","''")


def split_emails(raw):

    if raw is None:
        return []

    parts = re.split(r"[;,]+", raw)

    return [p.strip() for p in parts if p.strip()]

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 2B — Build email message (plain text only)

# COMMAND ----------
# Plain text preserves line breaks reliably across Outlook and other clients.
# HTML was removed because Outlook often collapses or mangles HTML formatting.

def build_email_message(from_email, reply_to, to_email, cc_list, subject, body):

    msg = EmailMessage()

    msg["From"] = from_email
    msg["To"] = to_email

    if cc_list:
        msg["Cc"] = ", ".join(cc_list)

    if reply_to:
        msg["Reply-To"] = reply_to

    msg["Subject"] = sanitize_text(subject)

    plain = sanitize_text(body)
    msg.set_content(plain)

    recipients = [to_email] + (cc_list or [])

    return msg, recipients

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 2D — Send email function

# COMMAND ----------

def send_email(
    from_email,
    smtp_user,
    smtp_password,
    to_email,
    cc_list,
    subject,
    body,
    reply_to=None
):

    to_email = clean_email(to_email)

    cc_list = [
        clean_email(x)
        for x in (cc_list or [])
        if clean_email(x)
    ]

    msg, recipients = build_email_message(
        from_email,
        reply_to,
        to_email,
        cc_list,
        subject,
        body
    )

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=30) as server:

        server.ehlo()
        server.starttls()
        server.ehlo()

        server.login(smtp_user, smtp_password)

        server.send_message(
            msg,
            from_addr=from_email,
            to_addrs=recipients
        )

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 3 — Find the latest emailRunId (the run we will send)

# COMMAND ----------

q = spark.table(emailQueueQcTable)

latestEmailRunId = q.select(
    F.max("emailRunId").alias("emailRunId")
).collect()[0]["emailRunId"]

print("latestEmailRunId:", latestEmailRunId)

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 4 — Select “latest run per study” rows to send (no duplicates)
# MAGIC
# MAGIC Rule:
# MAGIC
# MAGIC only rows from latestEmailRunId
# MAGIC
# MAGIC only one row per (studyId, sequence) (if duplicates exist, keep newest createdTsUtc)
# MAGIC
# MAGIC only unsent rows: sentTsUtc IS NULL and (sendStatus is null or not SENT)

# COMMAND ----------

from pyspark.sql.window import Window

q_latest = q.filter(
    F.col("emailRunId") == latestEmailRunId
)

w = Window.partitionBy("studyId","sequence")\
          .orderBy(F.col("createdTsUtc").desc())

to_send = (
    q_latest
    .withColumn("rn", F.row_number().over(w))
    .filter(F.col("rn")==1)
    .drop("rn")
    .filter(
        (F.col("sentTsUtc").isNull()) &
        (F.col("sendStatus").isNull() |
         (F.col("sendStatus")!="SENT"))
    )
)

n = to_send.count()

print(f"Emails to send: {n}")

display(
    to_send.select(
        "studyId",
        "sequence",
        "toEmail",
        "emailSubject",
        "createdTsUtc"
    )
)

# COMMAND ----------

# MAGIC %md
# MAGIC #### Cell 5 — Send emails + write back status to opsEmailQueueQc

# COMMAND ----------

rows = to_send.collect()

print(f"Processing {len(rows)} emails")

for r in rows:

    emailRunId = r["emailRunId"]
    studyId    = r["studyId"]
    sequence   = r["sequence"]

    toEmail = clean_email(r["toEmail"])
    cc_list = split_emails(r["ccEmails"])

    subject = sanitize_text(r["emailSubject"])
    body    = sanitize_text(r["emailBody"])


    if not toEmail:

        err_msg = "Missing toEmail"

        spark.sql(f"""
        UPDATE {emailQueueQcTable}
        SET sendStatus='FAILED',
            sentTsUtc=current_timestamp(),
            sendError='{esc_sql(err_msg)}'
        WHERE emailRunId='{emailRunId}'
        AND studyId='{studyId}'
        AND sequence='{sequence}'
        """)

        continue


    try:

        if not DRY_RUN:

            send_email(
                DEFAULT_FROM_EMAIL,
                DEFAULT_FROM_EMAIL,
                SMTP_PASSWORD,
                toEmail,
                cc_list,
                subject,
                body,
                DEFAULT_REPLY_TO
            )


        spark.sql(f"""
        UPDATE {emailQueueQcTable}
        SET sendStatus='SENT',
            sentTsUtc=current_timestamp(),
            sendError=NULL
        WHERE emailRunId='{emailRunId}'
        AND studyId='{studyId}'
        AND sequence='{sequence}'
        """)

        print(f"[OK] SENT {studyId}-{sequence}")


    except Exception as e:

        err = esc_sql(str(e))

        spark.sql(f"""
        UPDATE {emailQueueQcTable}
        SET sendStatus='FAILED',
            sentTsUtc=current_timestamp(),
            sendError='{err}'
        WHERE emailRunId='{emailRunId}'
        AND studyId='{studyId}'
        AND sequence='{sequence}'
        """)

        print(f"[FAIL] {studyId}-{sequence} -> {err}")